#!/bin/env bash

#--[2] send notif when update available

function recnote_notife_false() {

}


function recnote_notife_true() {

}

function recnote_notife() {

  recnote_notife_false
  recnote_notife_true

}
